/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticesTypeIDRouteImport } from './routes/notices/$typeID'
import { Route as NoticesTypeIDPostIDRouteImport } from './routes/notices/$typeID.$postID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesTypeIDRoute = NoticesTypeIDRouteImport.update({
  id: '/notices/$typeID',
  path: '/notices/$typeID',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesTypeIDPostIDRoute = NoticesTypeIDPostIDRouteImport.update({
  id: '/$postID',
  path: '/$postID',
  getParentRoute: () => NoticesTypeIDRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notices/$typeID': typeof NoticesTypeIDRouteWithChildren
  '/notices/$typeID/$postID': typeof NoticesTypeIDPostIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notices/$typeID': typeof NoticesTypeIDRouteWithChildren
  '/notices/$typeID/$postID': typeof NoticesTypeIDPostIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notices/$typeID': typeof NoticesTypeIDRouteWithChildren
  '/notices/$typeID/$postID': typeof NoticesTypeIDPostIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notices/$typeID' | '/notices/$typeID/$postID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notices/$typeID' | '/notices/$typeID/$postID'
  id: '__root__' | '/' | '/notices/$typeID' | '/notices/$typeID/$postID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticesTypeIDRoute: typeof NoticesTypeIDRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$typeID': {
      id: '/notices/$typeID'
      path: '/notices/$typeID'
      fullPath: '/notices/$typeID'
      preLoaderRoute: typeof NoticesTypeIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$typeID/$postID': {
      id: '/notices/$typeID/$postID'
      path: '/$postID'
      fullPath: '/notices/$typeID/$postID'
      preLoaderRoute: typeof NoticesTypeIDPostIDRouteImport
      parentRoute: typeof NoticesTypeIDRoute
    }
  }
}

interface NoticesTypeIDRouteChildren {
  NoticesTypeIDPostIDRoute: typeof NoticesTypeIDPostIDRoute
}

const NoticesTypeIDRouteChildren: NoticesTypeIDRouteChildren = {
  NoticesTypeIDPostIDRoute: NoticesTypeIDPostIDRoute,
}

const NoticesTypeIDRouteWithChildren = NoticesTypeIDRoute._addFileChildren(
  NoticesTypeIDRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticesTypeIDRoute: NoticesTypeIDRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
